#lang racket/base
(provide (all-defined-out))

(struct ast:lvar (index) #:prefab)
(struct ast:ctxvar (index) #:prefab)
(struct ast:lambda (vars restvar body) #:prefab)
(struct ast:case-lambda (lambdas) #:prefab)
(struct ast:if (e1 e2 e3) #:prefab)
(struct ast:begin (es) #:prefab)
(struct ast:begin0 (e0 es) #:prefab)
(struct ast:let-values (clauses body) #:prefab)
(struct ast:letrec-values (clauses body) #:prefab)
(struct ast:lv-clause (vars rhs) #:prefab)
(struct ast:quote (datum) #:prefab)
(struct ast:wcm (e1 e2 e3) #:prefab)
(struct ast:app (cs fun args) #:prefab)

(struct ast:sample (cs dist label) #:prefab)
(struct ast:dscore (arg) #:prefab)
(struct ast:lscore (arg) #:prefab)
(struct ast:observe (dist value) #:prefab)
(struct ast:fail (arg) #:prefab)
(struct ast:mem (cs arg) #:prefab)
(struct ast:run-model (cs arg) #:prefab)

(define (wrap-begin es)
  (if (and (pair? es) (null? (cdr es))) (car es) (ast:begin es)))

(define (wrap-let-values clauses body)
  (if (null? clauses) body (ast:let-values clauses body)))
